### ISSUE TITLE
Which version of Keras and tensorflow are you using to run the code?

### ISSUE THREAD

**Issue by HuitingLiu** [fferroni/PhasedLSTM-Keras#6]
I try the combination of different versions, there are always some errors when running the examples. Could you please tell me your version information? Thank you.

**Comment by HuitingLiu** [comment]
Solved. This combination works.
Keras==1.2.2
tensorflow==1.0.1

**Comment by fferroni** [comment]
Hi, yes the latest Keras API 2.0 has changed a lot, along with tensorflow 1.0, so will try to update :-)

**Comment by fferroni** [comment]
Should work with latest Tensorflow/Theano/Keras  :-)

**Comment by fgvenegas** [comment]
I have the following error when I try to run with Tensorflow in the backend. Im using:

- Python 3.6.1
- Keras 2.0.2
- Tensorflow 1.0.0 

I run the 2 examples that are in the repository but it didn't work with anyone

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value phased_lstm_1/Variable
         [[Node: phased_lstm_1/Variable/read = Identity[T=DT_FLOAT, _class=["loc:@phased_lstm_1/Variable"], _device="/job:localhost/replica:0/task:0/cpu:0"](phased_lstm_1/Variable)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "untitled.py", line 31, in <module>
    main()
  File "untitled.py", line 23, in main
    model_lstm.fit(X, Y)
  File "/usr/local/lib/python3.6/site-packages/keras/models.py", line 845, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 1485, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 1140, in _fit_loop
    outs = f(ins_batch)
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2071, in __call__
    session = get_session()
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 153, in get_session
    _initialize_variables()
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 306, in _initialize_variables
    sess.run(tf.variables_initializer(uninitialized_variables))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value phased_lstm_1/Variable
         [[Node: phased_lstm_1/Variable/read = Identity[T=DT_FLOAT, _class=["loc:@phased_lstm_1/Variable"], _device="/job:localhost/replica:0/task:0/cpu:0"](phased_lstm_1/Variable)]]

Caused by op 'phased_lstm_1/Variable/read', defined at:
  File "untitled.py", line 31, in <module>
    main()
  File "untitled.py", line 19, in main
    model_plstm.add(PhasedLSTM(10, input_shape=(100, 2)))
  File "/usr/local/lib/python3.6/site-packages/keras/models.py", line 422, in add
    layer(x)
  File "/usr/local/lib/python3.6/site-packages/keras/layers/recurrent.py", line 252, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/topology.py", line 528, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python3.6/site-packages/phased_lstm_keras/PhasedLSTM.py", line 245, in build
    constraint=self.timegate_constraint)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/topology.py", line 364, in add_weight
    weight = K.variable(initializer(shape), dtype=K.floatx(), name=name)
  File "/usr/local/lib/python3.6/site-packages/phased_lstm_keras/PhasedLSTM.py", line 66, in _timegate_initializer
    dtype=dtype)
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 286, in variable
    v = tf.Variable(value, dtype=_convert_string_dtype(dtype), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 226, in __init__
    expected_shape=expected_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 344, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1490, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value phased_lstm_1/Variable
         [[Node: phased_lstm_1/Variable/read = Identity[T=DT_FLOAT, _class=["loc:@phased_lstm_1/Variable"], _device="/job:localhost/replica:0/task:0/cpu:0"](phased_lstm_1/Variable)]]
```

**Comment by fferroni** [comment]
Will try and check this weekend! If I recall, when pip installing it should
fetch Keras version 2.0.2. Which should use TF>1.0 and latest Theano.
Have you tried running the examples?

**Comment by fgvenegas** [comment]
I updated TF to 1.0.1
I can run both examples with Theano in backend but not with TF in the backend (even with the update to 1.0.1)
